"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import About from "./(home)/about/page";
import Contact from "./(home)/contact/page";
import { title } from "process";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata: Metadata = {
//   title: {
//     default: "welcome to Next.js",
//     template: "%s |next js",
//     absolute: "",
//   },

//   description: "hello",
// };

const navigation = [
  { title: "about", href: "/about" },
  { title: "contact", href: "/contact" },
  { title: "blog", href: "/blog" },
  { title: "product", href: "/products" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <div>
          {navigation.map((nav) => {
            const isActive =
              pathname === nav.href ||
              (pathname.startsWith(nav.href) && nav.href !== "/");
            return (
              <Link className={isActive ? "to-bue-500" : ""} href={nav.href}>
                {nav.title}
              </Link>
            );
          })}
        </div>
        {children}
      </body>
    </html>
  );
}
